language: python
python:
  - "2.7"
install: 
  - pip install . --use-mirrors
  - pip install -r requirements.txt
before_install:
  - sudo apt-get update
  - sudo apt-get install gdal-bin libproj-dev postgis postgresql-9.1-postgis
  - sudo bash ./create_template_postgis-1.5.sh
  - createdb -T template_postgis geoads_db -U postgres
script: 
  - django-admin.py test --settings=tests.settings customads geoads